(("definition" "\\begin{definition}AUTOLABEL\n\n\\end{definition}" nil)
 ("equation" "\\begin{equation}AUTOLABEL\n?\n\\end{equation}" nil)
 ("equation*" "\\begin{equation*}\n? \n\\end{equation*}" nil)
 ("exercise" "\\begin{exercise}[?]\n\n\\end{exercise}" nil)
 ("frame" "\\begin{frame}{ ? }\n\n\\end{frame}" nil)
 ("inparaenum" "\\begin{inparaenum}\n\\item ? \n\\end{inparaenum}" "\\item ?")
 ("inparaitem" "\\begin{inparaitem}\n\\item ?\n\\end{inparaitem}" "\\item ?")
 ("lemma" "\\begin{lemma}AUTOLABEL\n\n\\end{lemma}" nil)
 ("myenumerate" "\\begin{myenumerate}\n\\item ?\n\\end{myenumerate}" "\\item ?")
 ("myitemize" "\\begin{myitemize}\n\\item ?\n\\end{myitemize}" "\\item ?")
 ("proof" "\\begin{proof}?\n\n\\end{proof}" nil)
 ("proposition" "\\begin{proposition}AUTOLABEL\n\n\\end{proposition}" nil)
 ("theorem" "\\begin{theorem}AUTOLABEL\n\n\\end{theorem}" nil))
