((?0 ("\\varnothing" "\\emptyset"))
 (?1 ("\\ONE_{?}" "\\ONE_{\\{ ? \\}}"))
 (?3 ("\\square"))
 (?. ("\\cdot" "\\circ"))
 (?v ("\\vee" "\\bigvee"))
 (?u ("\\upsilon" "\\cup"))
 (?U ("\\Upsilon" "\\bigcup_{?}"))
 (?n ("\\nu" "\\cap"))
 (?N ("\\nabla" "\\bigcap_{?}"))
 (?& ("\\wedge" "\\bigwedge"))
 (?8 ("\\infty" "\\ast"))
 (?+ ("\\dagger" "\\oplus" "\\bigoplus"))
 (?- ("\\rightharpoonup" "\\hookrightarrow" "\\circlearrowleft"))
 (?= ("\\equiv" "\\iff" "\\Longleftrightarrow"))
 (?\] ("\\Rightarrow" "\\implies"))
 (?\[ ("\\Leftarrow" "\\impliedby"))
 (?~ ("\\sim" "\\approx" "\\propto"))
 (?* ("\\times" "\\otimes" "\\bigotimes"))
 (?e ("\\eps" "\\epsilon" "\\exp\\Big( ? \\Big)"))
 (?f ("\\varphi" "\\phi"))
 (?> ("\\mapsto" "\\longrightarrow" "\\rightrightarrows"))
 (?< ("\\lesssim" "\\preceq" "\\longleftarrow"))
 (?| ("\\perp" "\\mid" "\\parallel"))
 (?S ("\\Sigma" "\\sum_{?}^{}"))
 (?{ ("\\subset" "\\subsetneq"))
 (?} ("\\supset" "\\succ" "\\supsetneq")))

