(("Big(" "insert \\Bigl( \\Bigr)" "\\Bigl( ? \\Bigr" cdlatex-position-cursor nil nil t)
 ("Big*" "insert \\con[\\Big]{} macro for Big conditional probability" "\\con[\\Big ]{?}" cdlatex-position-cursor nil nil t)
 ("Big[" "insert \\Bigl[ \\Bigr]" "\\Bigl[ ? \\Bigr" cdlatex-position-cursor nil nil t)
 ("Big\\|" "insert \\Big\\lVert \\Big\\rVert " "\\Big\\lVert ? \\Big\\rVert " cdlatex-position-cursor nil nil t)
 ("Bigg(" "insert \\Biggl( \\Biggr)" "\\Biggl( ? \\Biggr" cdlatex-position-cursor nil nil t)
 ("Bigg*" "insert \\con[\\Bigg]{} macro for Bigg conditional probability" "\\con[\\Bigg ]{?}" cdlatex-position-cursor nil nil t)
 ("Bigg[" "insert \\Biggl[ \\Biggr]" "\\Biggl[ ? \\Biggr" cdlatex-position-cursor nil nil t)
 ("Bigg\\|" "insert \\Bigg\\lVert \\Bigg\\rVert " "\\Bigg\\lVert ? \\Bigg\\rVert " cdlatex-position-cursor nil nil t)
 ("Bigg{" "insert \\Biggl\\{ \\Biggr\\}" "\\Biggl\\{ ? \\Biggr\\" cdlatex-position-cursor nil nil t)
 ("Bigg|" "insert \\Bigg\\lvert \\Bigg\\rvert " "\\Bigg\\lvert ? \\Bigg\\rvert " cdlatex-position-cursor nil nil t)
 ("Big{" "insert \\Bigl\\{ \\Bigr\\}" "\\Bigl\\{ ? \\Bigr\\" cdlatex-position-cursor nil nil t)
 ("Big|" "insert \\Big\\lvert \\Big\\rvert " "\\Big\\lvert ? \\Big\\rvert " cdlatex-position-cursor nil nil t)
 ("aali" "insert equation" "\\left\\{ \n\\begin{aligned}\n? \n\\end{aligned}\\right." cdlatex-position-cursor nil nil t)
 ("alb" "Insert beamer alert block with overlay" "\\begin{alertblock}<+->{ ? } \n\n\\end{alertblock}" cdlatex-position-cursor nil t nil)
 ("alb*" "Insert beamer alert block without overlay" "\\begin{alertblock}{ ? } \n\n\\end{alertblock}" cdlatex-position-cursor nil t nil)
 ("big(" "insert \\bigl( \\bigr)" "\\bigl( ? \\bigr" cdlatex-position-cursor nil nil t)
 ("big*" "insert \\con[\\big]{} macro for big conditional probability" "\\con[\\big ]{?}" cdlatex-position-cursor nil nil t)
 ("big[" "insert \\bigl[ \\bigr]" "\\bigl[ ? \\bigr" cdlatex-position-cursor nil nil t)
 ("big\\|" "insert \\big\\lVert \\big\\rVert " "\\big\\lVert ? \\big\\rVert " cdlatex-position-cursor nil nil t)
 ("bigg(" "insert \\biggl( \\biggr)" "\\biggl( ? \\biggr" cdlatex-position-cursor nil nil t)
 ("bigg*" "insert \\con[\\bigg]{} macro for bigg conditional probability" "\\con[\\bigg ]{?}" cdlatex-position-cursor nil nil t)
 ("bigg[" "insert \\biggl[ \\biggr]" "\\biggl[ ? \\biggr" cdlatex-position-cursor nil nil t)
 ("bigg\\|" "insert \\bigg\\lVert \\bigg\\rVert " "\\bigg\\lVert ? \\bigg\\rVert " cdlatex-position-cursor nil nil t)
 ("bigg{" "insert \\biggl\\{ \\biggr\\}" "\\biggl\\{ ? \\biggr\\" cdlatex-position-cursor nil nil t)
 ("bigg|" "insert \\bigg\\lvert \\bigg\\rvert " "\\bigg\\lvert ? \\bigg\\rvert " cdlatex-position-cursor nil nil t)
 ("big{" "insert \\bigl\\{ \\bigr\\}" "\\bigl\\{ ? \\bigr\\" cdlatex-position-cursor nil nil t)
 ("big|" "insert \\big\\lvert \\big\\rvert " "\\big\\lvert ? \\big\\rvert " cdlatex-position-cursor nil nil t)
 ("blo" "Insert beamer block with overlay" "\\begin{block}<+->{ ? } \n\n\\end{block}" cdlatex-position-cursor nil t nil)
 ("blo*" "Insert beamer block WITHOUT overlay" "\\begin{block}{ ? } \n\n\\end{block}" cdlatex-position-cursor nil t nil)
 ("bn" "binomial" "\\binom{?}{}" cdlatex-position-cursor nil nil t)
 ("capl" "insert \\bigcap\\limits_{}^{}" "\\bigcap\\limits_{?}^{}" cdlatex-position-cursor nil nil t)
 ("case" "insert cases" "\\begin{cases}\n? & \\\\\n &\n\\end{cases}" cdlatex-position-cursor nil nil t)
 ("cd" "insert dotsb" "\\dotsb" nil nil t t)
 ("cd*" "insert \\con{} macro for conditional probability" "\\con{?}" cdlatex-position-cursor nil nil t)
 ("ce" "insert :=" "\\coloneq " nil nil nil t)
 ("cte" "insert citation using helm-bibtex" "" helm-bibtex-with-local-bibliography nil t nil)
 ("cupl" "insert \\bigcup\\limits_{}^{}" "\\bigcup\\limits_{?}^{}" cdlatex-position-cursor nil nil t)
 ("dd" "insert ddots" "\\ddots" nil nil t t)
 ("def" "insert definition env" "" cdlatex-environment ("definition") t nil)
 ("des" "insert description" "" cdlatex-environment ("description") t nil)
 ("ec" "insert =:" "\\eqcolon " nil nil nil t)
 ("eq" "insert pairs of \\[ \\]" "\\[ ? \\]" cdlatex-position-cursor nil t t)
 ("equ*" "insert unlabel equation" "" cdlatex-environment ("equation*") t nil)
 ("eq*" "insert equation without label" "\\begin{equation}\n?\n\\end{equation}" cdlatex-position-cursor nil t nil)
 ("exb" "Insert beamer example block with overlay" "\\begin{exampleblock}<+->{ ? } \n\n\\end{exampleblock}" cdlatex-position-cursor nil t nil)
 ("exb*" "Insert beamer example block without overlay" "\\begin{exampleblock}{ ? } \n\n\\end{exampleblock}" cdlatex-position-cursor nil t nil)
 ("exe" "Insert exercise" "\\begin{exercise}\n? \n\\end{exercise}" cdlatex-position-cursor nil t nil)
 ("fra" "insert frame (for beamer)" "" cdlatex-environment ("frame") t nil)
 ("hhl" "insert \\ \\hline" "\\\\ \\hline" nil nil t nil)
 ("hl" "insert \\hline" "\\hline" nil nil t nil)
 ("ipenu" "insert in paragraph enumerate" "" cdlatex-environment ("inparaenum") t nil)
 ("ipite" "insert in paragraph itemize" "" cdlatex-environment ("inparaitem") t nil)
 ("ld" "insert dotsc" "\\dotsc" nil nil t t)
 ("im" "insert \\implies" "\\implies" nil nil nil t)
 ("imb" "insert \\impliedby" "\\impliedby" nil nil nil t)
 ("lem" "insert lemma env" "" cdlatex-environment ("lemma") t nil)
 ("liml" "insert \\lim\\limits_{}" "\\lim\\limits_{?}" cdlatex-position-cursor nil nil t)
 ("lr<" "insert bra-ket" "\\langle ? \\rangle " cdlatex-position-cursor nil nil t)
 ("lr|" "insert \\lvert ? \\rvert " "\\lvert ? \\rvert " cdlatex-position-cursor nil nil t)
 ("myenu" "insert in my enumerate for beamer" "" cdlatex-environment ("myenumerate") t nil)
 ("myite" "insert in my itemize for beamer" "" cdlatex-environment ("myitemize") t nil)
 ("no" "insert \\lVert ? \\rVert " "\\lVert ? \\rVert " cdlatex-position-cursor nil nil t)
 ("ons" "" "\\onslide<?>{ }" cdlatex-position-cursor nil t t)
 ("pa" "insert pause" "\\pause" nil nil t nil)
 ("pro" "insert proof env" "" cdlatex-environment ("proof") t nil)
 ("prodl" "insert \\prod\\limits_{}^{}" " \\prod\\limits_{?}^{}" cdlatex-position-cursor nil nil t)
 ("prop" "insert proposition" "" cdlatex-environment ("proposition") t nil)
 ("rep" "insert phantom of math relation" "\\mathrel{\\phantom{?}}" cdlatex-position-cursor nil nil t)
 ("res" "insert restriction" "\\big\\vert" nil nil nil t)
 ("se" "insert \\{\\}" "\\{ ? \\}" cdlatex-position-cursor nil nil t)
 ("spl" "insert split" "" cdlatex-environment ("split") nil t)
 ("st" "stackrel" "\\stackrel{?}{}" cdlatex-position-cursor nil nil t)
 ("te" "insert text" "\\text{?}" cdlatex-position-cursor nil nil t)
 ("tf" "tiny fraction" "\\tfrac" nil nil nil t)
 ("thm" "insert theorem env" "" cdlatex-environment ("theorem") t nil)
 ("vd" "insert vdots" "\\vdots" nil nil t t))

